"""Sample a mixed blindable list of real and random AV outputs.

Real rows come from an existing decoded trace JSONL with `nla_output`.
Random rows are generated by sampling unit vectors in model space and decoding
them locally with the AV by default. Pass `--backend sglang` only when you
explicitly want to use an already-running SGLang server.
"""

import argparse
import html
import json
import os
from pathlib import Path
from typing import Any

import numpy as np
import torch

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_HF_HOME = _REPO_ROOT / "hf_cache"
os.environ.setdefault("HF_HOME", str(_DEFAULT_HF_HOME))
os.environ.setdefault("HF_HUB_CACHE", str(_DEFAULT_HF_HOME))
os.environ.setdefault("HF_XET_CACHE", str(_DEFAULT_HF_HOME / "xet"))

from nla.scripts.decode_token_activations import (  # noqa: E402
    SGLangDecoder,
    TransformersDecoder,
    _default_device,
    _torch_dtype,
)


_REAL_META_KEYS = (
    "row_index",
    "token_index",
    "token_id",
    "token_text",
    "char_start",
    "char_end",
    "is_special",
    "prefix_text",
    "activation_norm",
)


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open() as f:
        for line_no, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            if not isinstance(rec, dict):
                raise ValueError(f"{path}:{line_no}: expected a JSON object")
            rows.append(rec)
    return rows


def read_real_trace(path: Path) -> list[dict[str, Any]]:
    rows = []
    for i, rec in enumerate(_read_jsonl(path)):
        output = rec.get("nla_output")
        if not isinstance(output, str) or not output.strip():
            continue
        row = dict(rec)
        row["_trace_row_index"] = i
        rows.append(row)
    if not rows:
        raise ValueError(f"{path} has no rows with non-empty string nla_output")
    return rows


def split_counts(count: int, allow_odd: bool) -> tuple[int, int]:
    if count <= 0:
        raise ValueError("--count must be positive")
    if count % 2 != 0 and not allow_odd:
        raise ValueError("--count must be even unless --allow-odd is passed")
    real_count = count // 2
    random_count = count - real_count
    return real_count, random_count


def sample_unit_vector(d_model: int, seed: int) -> np.ndarray:
    if d_model <= 0:
        raise ValueError(f"d_model must be positive, got {d_model}")
    rng = np.random.default_rng(seed)
    v = rng.standard_normal(d_model).astype(np.float32)
    norm = float(np.linalg.norm(v))
    if norm == 0.0:
        raise AssertionError("standard_normal produced a zero vector")
    return (v / norm).astype(np.float32)


def _record_kind(kind: str, blind: bool, metadata: dict[str, Any] | None = None) -> dict[str, Any]:
    if not blind:
        return {"kind": kind}
    rec: dict[str, Any] = {"answer_kind": kind}
    if metadata:
        rec["answer_metadata"] = metadata
    return rec


def real_record(row: dict[str, Any], blind: bool) -> dict[str, Any]:
    meta = {"trace_row_index": row["_trace_row_index"]}
    for key in _REAL_META_KEYS:
        if key in row:
            meta[key] = row[key]
    rec = _record_kind("real", blind, meta)
    rec["output"] = row["nla_output"]
    if blind:
        return rec
    rec["trace_row_index"] = row["_trace_row_index"]
    for key in _REAL_META_KEYS:
        if key in row:
            rec[key] = row[key]
    return rec


def random_record(random_index: int, random_seed: int, vector: np.ndarray, output: str, blind: bool) -> dict[str, Any]:
    metadata = {
        "random_index": random_index,
        "random_seed": random_seed,
        "vector_norm": float(np.linalg.norm(vector)),
    }
    rec = _record_kind("random", blind, metadata)
    rec["output"] = output
    if not blind:
        rec.update(metadata)
    return rec


def build_mixed_records(
    real_rows: list[dict[str, Any]],
    decoder: Any,
    args: argparse.Namespace,
) -> list[dict[str, Any]]:
    real_count, random_count = split_counts(args.count, args.allow_odd)
    if len(real_rows) < real_count:
        raise ValueError(
            f"need {real_count} real rows for --count {args.count}, "
            f"but only found {len(real_rows)} valid rows in --real-trace"
        )

    d_model = int(decoder.client.cfg.d_model)
    rng = np.random.default_rng(args.seed)
    real_indices = rng.choice(len(real_rows), size=real_count, replace=False)
    random_seeds = rng.integers(0, 2**63 - 1, size=random_count, dtype=np.int64)

    records: list[dict[str, Any]] = []
    for idx in real_indices.tolist():
        records.append(real_record(real_rows[idx], args.blind))

    for random_index, seed_value in enumerate(random_seeds.tolist()):
        vector = sample_unit_vector(d_model, int(seed_value))
        output = decoder.generate(vector, args)
        records.append(random_record(random_index, int(seed_value), vector, output, args.blind))
        print(f"[random {random_index + 1}/{random_count}] seed={int(seed_value)}", flush=True)

    order = rng.permutation(len(records))
    mixed = [records[i] for i in order.tolist()]
    for sample_index, rec in enumerate(mixed):
        rec["sample_index"] = sample_index
    return mixed


def _json_for_script(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")


def _visible_kind(rec: dict[str, Any]) -> str:
    return str(rec.get("kind", "?"))


def render_html(records: list[dict[str, Any]], title: str, blind: bool) -> str:
    payload = _json_for_script(records)
    title_esc = html.escape(title)
    kind_css = " hidden" if blind else ""
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title_esc}</title>
<style>
:root {{
  color-scheme: light;
  --bg: #f5f7fa;
  --panel: #ffffff;
  --ink: #1f2430;
  --muted: #667085;
  --line: #d6dee8;
  --real: #0b6b4b;
  --random: #8a4d11;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}}
* {{ box-sizing: border-box; }}
body {{ margin: 0; background: var(--bg); color: var(--ink); }}
.topbar {{
  position: sticky;
  top: 0;
  z-index: 2;
  display: flex;
  justify-content: space-between;
  gap: 12px;
  align-items: center;
  padding: 12px 18px;
  border-bottom: 1px solid var(--line);
  background: #edf2f7;
}}
h1 {{ margin: 0; font-size: 18px; line-height: 1.2; letter-spacing: 0; }}
.summary {{ color: var(--muted); font-size: 12px; font-weight: 700; }}
.wrap {{ display: grid; gap: 10px; padding: 14px 18px 22px; }}
.card {{
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--panel);
  box-shadow: 0 1px 3px rgb(16 24 40 / 10%);
  overflow: hidden;
}}
.head {{
  display: flex;
  justify-content: space-between;
  gap: 10px;
  padding: 9px 11px;
  border-bottom: 1px solid var(--line);
  background: #fbfcfe;
}}
.idx {{ color: var(--muted); font-size: 12px; font-weight: 800; }}
.kind {{
  border-radius: 999px;
  padding: 3px 8px;
  background: #eef5f1;
  color: var(--real);
  font-size: 11px;
  font-weight: 800;
  text-transform: uppercase;
}}
.kind.random {{ background: #fff4e6; color: var(--random); }}
.hidden {{ display: none; }}
pre {{
  margin: 0;
  padding: 11px;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
  font: 13px/1.42 ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
}}
</style>
</head>
<body>
<div class="topbar">
  <h1>{title_esc}</h1>
  <div class="summary">{len(records)} outputs{", blind" if blind else ""}</div>
</div>
<main class="wrap" id="cards"></main>
<script>
const records = {payload};
const cards = document.getElementById("cards");
for (const rec of records) {{
  const kind = rec.kind || rec.answer_kind || "?";
  const card = document.createElement("article");
  card.className = "card";
  const head = document.createElement("div");
  head.className = "head";
  const idx = document.createElement("div");
  idx.className = "idx";
  idx.textContent = `#${{rec.sample_index}}`;
  const badge = document.createElement("div");
  badge.className = `kind ${{kind}}{kind_css}`;
  badge.textContent = kind;
  head.append(idx, badge);
  const pre = document.createElement("pre");
  pre.textContent = rec.output || "";
  card.append(head, pre);
  cards.append(card);
}}
</script>
</body>
</html>
"""


def _write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")


def _load_decoder(args: argparse.Namespace) -> Any:
    if args.backend == "sglang":
        return SGLangDecoder(args.checkpoint, args.sglang_url)
    return TransformersDecoder(
        args.checkpoint,
        args.device,
        args.torch_dtype,
        device_map=args.device_map,
    )


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--real-trace", required=True, help="JSONL trace with real AV outputs in nla_output.")
    p.add_argument("--checkpoint", required=True, help="Local NLA AV checkpoint dir with nla_meta.yaml.")
    p.add_argument("--output", required=True, help="Output mixed JSONL path.")
    p.add_argument("--html-output", help="Optional HTML viewer output path.")
    p.add_argument("--count", type=int, default=100)
    p.add_argument("--allow-odd", action="store_true", help="Allow odd --count; the extra row is random.")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--blind", action="store_true", help="Hide kind in visible fields; preserve answer_kind.")
    p.add_argument("--backend", choices=("sglang", "transformers"), default="transformers")
    p.add_argument("--sglang-url", default="http://localhost:30000")
    p.add_argument("--device", default=_default_device(), help="For --backend transformers: cuda, mps, or cpu.")
    p.add_argument(
        "--device-map",
        default="none",
        help='For --backend transformers: Accelerate device map, e.g. "auto"; "none" moves the whole model to --device.',
    )
    p.add_argument("--torch-dtype", type=_torch_dtype, default=torch.bfloat16)
    p.add_argument("--temperature", type=float, default=0.7)
    p.add_argument("--max-new-tokens", type=int, default=200)
    p.add_argument("--raw", action="store_true", help="Keep raw AV output instead of extracting explanation tags.")
    args = p.parse_args()

    real_rows = read_real_trace(Path(args.real_trace))
    decoder = _load_decoder(args)
    records = build_mixed_records(real_rows, decoder, args)

    out = Path(args.output)
    _write_jsonl(out, records)
    print(f"wrote {len(records)} mixed outputs to {out}", flush=True)

    if args.html_output:
        html_out = Path(args.html_output)
        html_out.parent.mkdir(parents=True, exist_ok=True)
        html_out.write_text(render_html(records, title="Mixed Real/Random AV Outputs", blind=args.blind))
        print(f"wrote HTML viewer to {html_out}", flush=True)


if __name__ == "__main__":
    main()
